name: yansnet
description: A Yansoki Social Network
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  dio: ^5.4.3+1
  dio_cache_interceptor: ^3.5.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_lints: ^3.0.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.7
  go_router: ^13.2.0
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  image_picker: ^1.0.7
  intl: ^0.20.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  very_good_analysis: ^5.1.0

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  swagger_dart_code_generator: ^2.11.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - shorebird.yaml
    - assets/images/Empty-bro 1.png
    - assets/images/wifi_off.png
